#!/bin/bash

#changing build type, without re-building edk2 can cause missing OVMF bios in test-gvt-g.sh
export BUILD_TYPE="RELEASE" # DEBUG | RELEASE
export REPO_DIR="$(pwd)"
export TEST_DIR="@TEST"
export WORKSPACE="$REPO_DIR/@BUILD"

#change the below paths to point to edk2 & edk2-platforms repos
export EDK2_PATH="$REPO_DIR/../edk2"
export EDK2_PLATFORMS_PATH="$REPO_DIR/../edk2-platforms"

#you can make up a uuid, change the rest if needed
export VIRT_GPU_UUID="3619fb61-cd4a-41d9-bd70-d0a7ea735388"
export GPU_DEV="0000:00:02.0"
export GVT_MODE="i915-GVTg_V5_4"
