#!/bin/bash

if [ -z "$REPO_DIR" ]; then
    export REPO_DIR=$(realpath .)
fi

#change the below paths to point to edk2 & edk2-platforms repos
if [ -z "$EDK2_PATH" ]; then
    export EDK2_PATH="$REPO_DIR/../edk2"
fi
if [ -z "$EDK2_PLATFORMS_PATH" ]; then
    export EDK2_PLATFORMS_PATH="$REPO_DIR/../edk2-platforms"
fi

#changing build type, without re-building edk2 can cause missing OVMF bios in test-gvt-g.sh
export BUILD_TYPE="RELEASE" # DEBUG | RELEASE
export TEST_DIR="@TEST"
export WORKSPACE="$REPO_DIR/@BUILD"

#you can make up a uuid, change the rest if needed
export VIRT_GPU_UUID="3619fb61-cd4a-41d9-bd70-d0a7ea735388"
export GPU_DEV="0000:00:02.0"
export GVT_MODE="i915-GVTg_V5_4"
